export interface Book
{
  _id : number | null,
  isbn : Number,
  mode?: 'new' | 'edit' | 'read',
  title : string,
  author : String,
  series? : String,
  volume? : Number,
  publisher? : String,
  edition? : Number,
  translation? : String,
  orgLang? : String,
  orgTitle? : String,
  ilustrations? : String,
  type? : [],
  cover? : String,
  pages? : Number,
  size? : String,
  favourite?: Boolean,
  read?: Boolean,
  wishlist?: Boolean,
  priceOrg?: String,
  price?: String,
  rating? : Number,
  myTag? : [],
  decription? : String,
  comment?: string
}
