
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatRadioModule } from '@angular/material/radio';
import { MatTableModule } from '@angular/material/table';
import { Book, ExternalBook } from 'src/shared/models';
import { TranslationService } from 'src/shared/services';
import { ISBNService } from '../../isbn-service/isbn.service';

import { isEmpty } from 'lodash';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';

@Component({
  selector: 'app-merge-data-info',
  imports: [
    FormsModule,
    MatTableModule,
    MatRadioModule,
    MatProgressSpinnerModule
],
  templateUrl: './merge-data-info.component.html',
  styleUrl: './merge-data-info.component.scss'
})
export class MergeDataInfoComponent {
  private isbnService = inject(ISBNService)
  private translationService = inject(TranslationService)

  externalBooksArray = this.isbnService.getExternalBookList()

  columns: any[] = [];
  displayedColumns: string[] = [];
  dataSource: ExternalBook[] = [];
  selectedSource: any;

  generateColumns(booksArray: ExternalBook[] | []) {
    if (!isEmpty(booksArray)) {
      const uniqueKeys = new Set(booksArray.reduce((acc: any, book: any) => {
        Object.keys(book).forEach(key => acc.add(key));
        return acc;
      }, new Set()));

      const uniqueKeysArray = [...uniqueKeys]

      // todo key type to fix
      const autoGeneratedColumns = uniqueKeysArray.map((key: any) => {
        const translatedKey = this.translationService.getTranslations(`book.${key}`);
        return {
          columnDef: key,
          header: translatedKey ? translatedKey.charAt(0).toUpperCase() + translatedKey.slice(1) : "", // Simple capitalization for header
          cell: (element: Book) => typeof element[(key as keyof Book)] !== "undefined" ? element[(key as keyof Book)] : "",
        }
      });

      return autoGeneratedColumns
    }
    return []
  }

  isSticky(item: string) {
    // return item === "selected" || item === "title"
    return item === "selected"
  }

  createDataSource(bookList: ExternalBook[]): ExternalBook[] {
    bookList = bookList.map(rawBook => {
      const book = rawBook
      const { selected, ...rest } = book;
      const selectedValue = typeof selected === 'undefined' ? false : selected;
      return { selected: selectedValue, ...rest } as ExternalBook;
    })
    this.selectedSource = bookList.find(item => item.selected)
    return bookList
  }

  async ngOnInit(): Promise<void> {
    this.externalBooksArray.subscribe(bookList => {
      const booksArray = this.createDataSource(bookList);
      this.dataSource = booksArray;
      this.columns = this.generateColumns(booksArray)
      this.displayedColumns = this.columns.map(c => c.columnDef);
    });
  }


  // fix this on init
  selectDataSource() {
    for (const book of this.dataSource) {
      book.selected = false;
    }
    const newSource = this.dataSource.find(book => book.source === this.selectedSource.source);
    (newSource as ExternalBook).selected = true
    this.isbnService.updateExternalBookList(this.dataSource)
  }
}
