import { Translations } from "@lib/shared";

export const translations: Translations = {
  common: {
    addNew: "Dodaj nową",
    choose: "wybierz",
    list: "Lista",
    add_new: "Dodaj nową",
    user: "Użytkownik",
    login: "Zaloguj",
    logout: "wyloguj",
  },
  book: {
    _id: "",
    source: "źródło",
    isbn: "isbn",
    title: "tytuł",
    author: "autor",
    comment: "komentarz",
    cover: "okładka",
    decription: "opis",
    dimensions: "wymiary",
    height: "wysokość",
    width: "szerokość",
    thickness: "grubość",
    edition: "edycja",
    favourite: "ulubiona",
    ilustrations: "ilustracje",
    orgLang: "język orginału",
    pages: "ilość stron",
    price: "cena",
    priceOrg: "cena oryginalna",
    publishedDate: "data wydania",
    publisher: "wydawca",
    series: "seria",
    size: "rozmiar",
    translation: "tłumaczenie",
    type: "typ",
    volume: "tom",
    read: "przeczytana",
    myTag: "moje tagi",
    orgTitle: "tytuł oryginalny",
    mode: "",
    rating: "ocena",
    wishlist: "lista życzeń",
  }
}